/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Xalary, XalaryInterface } from "../../contracts/Xalary";

const _abi = [
  {
    inputs: [],
    name: "deployFixedRateAgreement",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50607780601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80636a02e29c14602d575b600080fd5b604080516001815290519081900360200190f3fea264697066735822122078d8f3af3fc2051eec0efaa9e6922582048fd524088e8b3f07720fbca729c79964736f6c63430008180033";

type XalaryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: XalaryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Xalary__factory extends ContractFactory {
  constructor(...args: XalaryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Xalary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Xalary__factory {
    return super.connect(runner) as Xalary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): XalaryInterface {
    return new Interface(_abi) as XalaryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Xalary {
    return new Contract(address, _abi, runner) as unknown as Xalary;
  }
}
