/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as agreementSol from "./Agreement.sol";
export type { agreementSol };
import type * as batchSol from "./Batch.sol";
export type { batchSol };
import type * as testTokenContractSol from "./TestTokenContract.sol";
export type { testTokenContractSol };
export type { AgreementFactory } from "./AgreementFactory";
export type { FixedRateAgreement } from "./FixedRateAgreement";
export type { Lock } from "./Lock";
export type { PayAsYouGoAgreement } from "./PayAsYouGoAgreement";
export type { Xalary } from "./Xalary";
