/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as batchSol from "./Batch.sol";
export type { batchSol };
import type * as testTokenContractSol from "./TestTokenContract.sol";
export type { testTokenContractSol };
import type * as contractDeps from "./contract-deps";
export type { contractDeps };
export type { Agreement } from "./Agreement";
export type { AgreementFactory } from "./AgreementFactory";
export type { FixedRateAgreement } from "./FixedRateAgreement";
export type { Lock } from "./Lock";
export type { PayAsYouGoAgreement } from "./PayAsYouGoAgreement";
export type { Xalary } from "./Xalary";
