/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRelayer,
  IRelayerInterface,
} from "../../../../../../../contracts/contract-deps/wormhole-sdk/src/interfaces/CCTPInterfaces/IRelayer";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "originalMessage",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "originalAttestation",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "newMessageBody",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "newDestinationCaller",
        type: "bytes32",
      },
    ],
    name: "replaceMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "destinationDomain",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "recipient",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "messageBody",
        type: "bytes",
      },
    ],
    name: "sendMessage",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "destinationDomain",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "recipient",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "destinationCaller",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "messageBody",
        type: "bytes",
      },
    ],
    name: "sendMessageWithCaller",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRelayer__factory {
  static readonly abi = _abi;
  static createInterface(): IRelayerInterface {
    return new Interface(_abi) as IRelayerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRelayer {
    return new Contract(address, _abi, runner) as unknown as IRelayer;
  }
}
