/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cctpInterfaces from "./CCTPInterfaces";
export type { cctpInterfaces };
import type * as iWormholeRelayerSol from "./IWormholeRelayer.sol";
export type { iWormholeRelayerSol };
export type { IERC20 } from "./IERC20";
export type { ITokenBridge } from "./ITokenBridge";
export type { IWETH } from "./IWETH";
export type { IWormhole } from "./IWormhole";
export type { IWormholeReceiver } from "./IWormholeReceiver";
